data=xlsread('I:\数学建模国赛真\data13.xls');
x=data(243:691,[7 8]);
y=data(243:691,6);
x=x';
y=y';
[XN,XS1]=mapminmax(x);
[YN YS1]=mapminmax(y);
net1=newrb(XN,YN)
lat=input('请输入纬度');
lon=input('请输入经度');
x=[lat lon];
xn=mapminmax('apply',x,XS1);
y0=sim(net1,xn);
y1=mapminmax('reverse',y0,YS1);
%net2=feedforwardnet(4);
%net2=train(net2,XN,YN);
%yn2=net2(xn);
%y2=mapminmax('reverse',yn2,PS2);